version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - catmidas-bd

  catalogo:
    build:
      context: .  # Usa o Dockerfile localizado no diretório atual
    image: catalogo
    container_name: catalogo-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - catmidas-bd

networks:
  catmidas-bd: 
    driver: bridge 

volumes:
  postgres-data:
    driver: local
